# Generated by Django 3.2.9 on 2022-01-20 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(default='COE', max_length=10)),
                ('branch_name', models.CharField(default='Computer Engineering', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default=None, max_length=100)),
                ('course_name', models.CharField(default=None, max_length=200)),
                ('course_credit', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.designation')),
            ],
        ),
        migrations.CreateModel(
            name='TotalLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveName', models.CharField(blank=True, max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2021)),
            ],
        ),
        migrations.CreateModel(
            name='UserLeaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(null=True)),
                ('reason', models.TextField()),
                ('substitute_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('rejected', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='admin', to='main.staff')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.totalleaves')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.staff')),
                ('substitute', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='Substitute', to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='UserLeavesTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('leave_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.totalleaves')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LEAVE', 'Leave'), ('TECH', 'Technician'), ('TTC', 'Time Table Change'), ('LEAVE_ACCEPTED', 'Leave Accepted'), ('LEAVE_REJECTED', 'Leave Rejected')], default='LEAVE', max_length=20)),
                ('taskId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(max_length=10)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='NILL', max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branches')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultycourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultygroups')),
            ],
        ),
        migrations.AddField(
            model_name='facultygroups',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AddField(
            model_name='facultygroups',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups'),
        ),
        migrations.AddField(
            model_name='facultycourse',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1024)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lab')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryofdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('work_Done', models.TextField(blank=True, max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.staff')),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
                ('who_resolved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolver', to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=2000)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultycourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultygroups')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lab')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
