# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('StaffMember', 'StaffMember'), ('Technician', 'Technician')], default='SM', max_length=30),
        ),
    ]
