# Generated by Django 3.2.9 on 2021-11-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('SM', 'StaffMember'), ('Th', 'Technician')], default='SM', max_length=2),
        ),
    ]
