# Generated by Django 3.2.9 on 2021-11-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211130_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='username',
            new_name='tech_id',
        ),
    ]
