# Generated by Django 3.2.9 on 2021-12-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_username_technician_tech_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField()),
                ('special', models.IntegerField()),
                ('restricted', models.IntegerField()),
                ('medical', models.IntegerField()),
                ('earned', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='computers',
            name='lab_id',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='Lab_id',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='who_resolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='work_Done',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='lab',
            name='floor',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='lab',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Computers',
        ),
        migrations.AddField(
            model_name='leaves',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AddField(
            model_name='devices',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lab'),
        ),
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryofdevice'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.devices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.designation'),
            preserve_default=False,
        ),
    ]
