# Generated by Django 3.2.9 on 2021-12-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211222_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.devices'),
        ),
    ]
