# Generated by Django 3.2.9 on 2021-12-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211224_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
    ]
