# Generated by Django 3.2.9 on 2021-12-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
