# Generated by Django 3.2.9 on 2021-12-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
