# Generated by Django 3.2.9 on 2021-12-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
