# Generated by Django 3.2.9 on 2021-12-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
