# Generated by Django 3.2.9 on 2021-12-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField()),
                ('special', models.IntegerField()),
                ('restricted', models.IntegerField()),
                ('medical', models.IntegerField()),
                ('earned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLeavesTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField()),
                ('special', models.IntegerField()),
                ('restricted', models.IntegerField()),
                ('medical', models.IntegerField()),
                ('earned', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='UserLeaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('reason', models.TextField()),
                ('substitute_reply', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.staff')),
                ('substitute', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='Substitute', to='main.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='Leaves',
        ),
    ]
