# Generated by Django 3.2.9 on 2021-12-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211228_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalleaves',
            name='casual',
        ),
        migrations.RemoveField(
            model_name='totalleaves',
            name='earned',
        ),
        migrations.RemoveField(
            model_name='totalleaves',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='totalleaves',
            name='restricted',
        ),
        migrations.RemoveField(
            model_name='totalleaves',
            name='special',
        ),
        migrations.AddField(
            model_name='totalleaves',
            name='LeaveName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='totalleaves',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='YearWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.totalleaves')),
            ],
        ),
    ]
