# Generated by Django 3.2.9 on 2021-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20211229_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearwise',
            name='leave',
        ),
        migrations.AddField(
            model_name='yearwise',
            name='leave',
            field=models.ManyToManyField(to='main.TotalLeaves'),
        ),
    ]
