# Generated by Django 3.2.9 on 2021-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20211229_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearwise',
            name='leave',
        ),
        migrations.AddField(
            model_name='yearwise',
            name='LeaveName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='yearwise',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
