# Generated by Django 3.2.9 on 2021-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211229_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearWise',
        ),
        migrations.AddField(
            model_name='totalleaves',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
