# Generated by Django 3.2.9 on 2021-12-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211229_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavestaken',
            name='casual',
        ),
        migrations.RemoveField(
            model_name='userleavestaken',
            name='earned',
        ),
        migrations.RemoveField(
            model_name='userleavestaken',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='userleavestaken',
            name='restricted',
        ),
        migrations.RemoveField(
            model_name='userleavestaken',
            name='special',
        ),
        migrations.AddField(
            model_name='userleavestaken',
            name='Count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userleavestaken',
            name='leave_taken',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
