# Generated by Django 3.2.9 on 2022-01-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userleavestatus',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.totalleaves'),
        ),
    ]
