# Generated by Django 3.2.9 on 2022-01-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_userleavestatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userleavestatus',
            old_name='approval',
            new_name='admin_approval',
        ),
        migrations.RenameField(
            model_name='userleavestatus',
            old_name='substitute_reply',
            new_name='substitute_approval',
        ),
    ]
