# Generated by Django 3.2.9 on 2022-01-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220105_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='who_resolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolver', to='main.staff'),
        ),
    ]
