# Generated by Django 3.2.9 on 2022-01-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_complaint_who_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.staff'),
            preserve_default=False,
        ),
    ]
