# Generated by Django 3.2.9 on 2022-01-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20220106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('TECH', 'Technician'), ('TTC', 'Time Table Change'), ('LEAVE_ACCEPTED', 'Leave Accepted'), ('LEAVE_REJECTED', 'Leave Rejected')], default='LEAVE', max_length=20),
        ),
    ]
