# Generated by Django 3.2.9 on 2022-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='taskId',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
