# Generated by Django 3.2.9 on 2022-01-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_notification_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavestatus',
            name='admin',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='main.staff'),
            preserve_default=False,
        ),
    ]
