# Generated by Django 3.2.9 on 2022-01-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_userleavestatus_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavestatus',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='main.staff'),
        ),
    ]
