# Generated by Django 3.2.9 on 2022-01-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_userleavestatus_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavestatus',
            name='admin',
        ),
    ]
