# Generated by Django 3.2.9 on 2022-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_complaint_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavestatus',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
