# Generated by Django 3.2.9 on 2022-01-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_userleavestatus_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavestatus',
            name='isActive',
        ),
    ]
