# Generated by Django 3.2.9 on 2022-01-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_currenttypeleaves_yearleaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearleaves',
            name='publishDate',
            field=models.DateTimeField(),
        ),
    ]
