# Generated by Django 3.2.9 on 2022-01-12 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_yearleaves_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearleaves',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 9, 11, 49, 151965, tzinfo=utc)),
        ),
    ]
