# Generated by Django 3.2.9 on 2022-01-12 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_yearleaves_publishdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userleavestatus',
            old_name='date_time',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='userleavestatus',
            name='to_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yearleaves',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 12, 27, 12, 239512, tzinfo=utc)),
        ),
    ]
