# Generated by Django 3.2.9 on 2022-01-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_class_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(default='COE', max_length=10)),
                ('branch_name', models.CharField(default='Computer Engineering', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='NILL', max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branches')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.facultygroups'),
            preserve_default=False,
        ),
    ]
