# Generated by Django 3.2.9 on 2022-01-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20220117_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultycourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultygroups')),
            ],
        ),
    ]
